version: "3.9"
services:
  opa:
    image: openpolicyagent/opa:edge-rootless
    ports:
      - "8181:8181"
    command:
      - "run"
      - "--server"
      - "--log-format=json-pretty"
      - "/opa_configs/policy.rego"
    volumes:
      - ./opa_configs/policy.rego:/opa_configs/policy.rego

  app:
    build: .
    command: >
      sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - opa
    restart: on-failure